`timescale 1ns / 1ps
/*
Name: Jenico Preston
R-Number: R11911335
Assignment: Project 5

Purpose:
This module implements the 32-bit ALU used in the execute stage of the CPU.
The ALU performs arithmetic, logic, shift, NOT, and pass-through operations
based on the 4-bit alu_op control signal from the instruction decoder.

Supported operations:
ADD, SUB, AND, OR, XOR, NOT, shift left, shift right, and PASS.

The zero output is asserted when the ALU result is 0. This can be used by
branch logic or debugging to detect zero results.
*/

module alu32(
    input  wire [31:0] a,
    input  wire [31:0] b,
    input  wire [3:0]  alu_op,
    output reg  [31:0] result,
    output wire        zero
);

    // ============================================================
    // ALU Operation Codes
    // ============================================================
    // These values must match the ALU control values generated by
    // the instruction decoder.
    localparam ALU_ADD  = 4'd0;
    localparam ALU_SUB  = 4'd1;
    localparam ALU_AND  = 4'd2;
    localparam ALU_OR   = 4'd3;
    localparam ALU_XOR  = 4'd4;
    localparam ALU_NOT  = 4'd5;
    localparam ALU_SHL  = 4'd6;
    localparam ALU_SHR  = 4'd7;
    localparam ALU_PASS = 4'd8;

    // ============================================================
    // Combinational ALU Logic
    // ============================================================
    // The ALU output updates immediately whenever the inputs or
    // operation code change.
    always @(*) begin
        case (alu_op)
            ALU_ADD:  result = a + b;        // Addition
            ALU_SUB:  result = a - b;        // Subtraction
            ALU_AND:  result = a & b;        // Bitwise AND
            ALU_OR:   result = a | b;        // Bitwise OR
            ALU_XOR:  result = a ^ b;        // Bitwise XOR
            ALU_NOT:  result = ~a;           // Bitwise NOT of operand A
            ALU_SHL:  result = a << b[4:0];  // Shift left by lower 5 bits of B
            ALU_SHR:  result = a >> b[4:0];  // Shift right by lower 5 bits of B
            ALU_PASS: result = b;            // Pass operand B, used for LD immediate
            default:  result = 32'd0;        // Safe default for unused ALU codes
        endcase
    end

    // ============================================================
    // Zero Flag
    // ============================================================
    // This flag is high when the current ALU result equals zero.
    assign zero = (result == 32'd0);

endmodule
